name: Commerce Product taxonomy filter by name
type: module
description: 'Enables the categorization of commerce product.'
package: Commerce
core_version_requirement: ^8.8 || ^9.0
dependencies:
  - commerce:commerce
# version: '1.0.0'
# project: 'product_taxonomy_term_name_depth'

# Information added by Drupal.org packaging script on 2021-06-22
version: '1.0.0'
project: 'product_taxonomy_term_name_depth'
datestamp: 1624341601
